### ISSUE TITLE
Conflict with plugin Calendar

### ISSUE THREAD

**Issue by melsophos** [xldenis/obsidian-latex#3] opened 2021-02-17 18:54 UTC
There seems to be a conflict with the plugin [Calendar](https://github.com/liamcain/obsidian-calendar-plugin): when both `obsidian-latex` and `calendar` are enabled, commands defined in `preamble.sty` are not recognized. If I disable the Calendar plugin, then it works well again.

I have Obsidian v0.11.1, Calendar v 1.5.1 and Extended Mathjax v0.1.0. Since I don't know from which side the problem comes from, I am also posting on the other plugin bug tracker.

**Comment by xldenis** [comment] 2021-02-17 21:06
ooh interesting, I'll take a look at this tomorrow. Could you open your console and check for any error messages?

**Comment by melsophos** [comment] 2021-02-17 22:40
I did not find any specific error message in the console, but here are the logs in case: [console_obsidian.log](https://github.com/xldenis/obsidian-latex/files/5999049/console_obsidian.log)

I have also opened an issue at [Calendar](https://github.com/liamcain/obsidian-calendar-plugin/issues/143).

**Comment by xldenis** [comment] 2021-02-18 09:46
I've installed Calendar v1.5.3 and I have Obsidian v0.11.0 and I'm unable to reproduce the issue you describe. 

I have a few questions:

- What OS are you on? 
- Do you have any other plugins installed? Can you reproduce this with *only* Calendar and MathJax Extended?
- Is every command in`preamble.sty` affected? Your image in the other issue shows problems with `\dd`. 
- If you move the `\newcommand` into your markdown file does it fix things? 
- Can you share your preamble.sty? Or ideally a minimal vault that recreates the issue.

Thanks for reporting :)

**Comment by melsophos** [comment] 2021-02-18 15:36
- I have tried on Fedora 33 and Ubuntu 20.10.
- The problem still persisted after disabling all plugins except Calendar and MathJax Extended, although I did not uninstall them completely and I did not disabling core plugins.
- All commands are affected. The images had just one particular example, but I tried with different commands. I also tested with just one command in the preamble (`\dd` here) and the problem is still here.
- My preamble is: [preamble.txt](https://github.com/xldenis/obsidian-latex/files/6003969/preamble.txt)
- If I insert the command definition inside Latex in the markdown note, then it works. But here it becomes weird: after I did this following your post, it seems that the problem is gone, even after restarting Obsidian…
- I will try to create a minimal vault with the problem (if I manage to recreate it).

**Comment by xldenis** [comment] 2021-02-19 11:31
Let me know :) If the problem is gone then all the better! Weird that this would be transient though...

**Comment by melsophos** [comment] 2021-02-19 16:47
The problem came back this morning and disappeared again (and this time I cannot relate it to any specific action I did). Honestly, I am very puzzled… I will try to create a vault with the problem and let you know if I get any insight in-between.

**Comment by xldenis** [comment] 2021-02-19 17:46
agh!! that sounds super frustrating, I'm sorry I can't be much more help :P

**Comment by melsophos** [comment] 2021-03-31 01:00
I have understood a bit more how it appears: if, when the app starts (fresh or reload), there is a pane in preview mode for a note containing some Latex (with or without user-defined commands) which is opened, then user-defined commands don't work. If there is no such pane, then commands will work fine for the session. I checked again that if the the Calendar extension is disabled, then it works well even when a note preview with Latex is opened at the beginning.

Strangely, I could not reproduce the bug in a new vault with only two simple files (one with and one without Latex) and the same plugins.

**Comment by xldenis** [comment] 2021-03-31 09:49
Oh wow I think I just had an idea about what could be causing this. I wonder if the plugin loading order could be responsible cause a race to happen. We rely on this plugin loading before obsidian has a chance to render any latex (since we need to first load the preamble). I wonder if the `Calendar` causes it to take too long to load. I'm going to see if I can force Obsidian to do a full-rerender after loading the mathjax preamble. I bet this will also fix the windows issues!

**Comment by melsophos** [comment] 2021-04-01 15:49
I don't know if Obsidian is also indexing notes when starting, but this may explain why the problem appears only in my standard vault (which is quite large) and not in the test one, which is small.

**Comment by xldenis** [comment] 2021-04-01 16:31
Yea this just screams race condition to me, that narrows it down quite a bit!

**Comment by xldenis** [comment] 2021-04-26 21:49
I believe that I finally have a solution for this coming!

**Comment by xldenis** [comment] 2021-05-10 19:41
I believe that this is now fixed in the latest version.

**Closed by xldenis** 2021-05-10 19:41 UTC
