### ISSUE TITLE
Preamble not recognised in Obsidian v0.11.3

### ISSUE THREAD

**Issue by ch869** [xldenis/obsidian-latex#5] opened 2021-03-04 17:41 UTC
None of the content in `preamble.sty` seems to load anymore upon updating to Obsidian v0.11.3, even when reloading Obsidian. It was working fine in v0.11.0, and this isn't due to plugin conflicts as I have tried disabling all other plugins. I currently have Extended MathJax v0.1.0.

**Comment by xldenis** [comment] 2021-03-04 21:02
Hmmm... I just updated my Obsidian build and can't reproduce. Let me take a further look. Can you share your `preamble.sty` please?

**Comment by ch869** [comment] 2021-03-04 21:53
[Here's](https://github.com/xldenis/obsidian-latex/files/6086808/preamble.txt) my `preamble.sty` in plaintext (so I can upload it).

**Comment by ch869** [comment] 2021-03-04 22:10
Okay, this is very odd - I was investigating this issue further, and everything worked in a new vault, including when I added back all my previous settings, CSS snippets, and plugins, reloading throughout. I then disabled everything on my main vault, reloaded, and the error persisted, but when I re-enabled everything and reloaded, it suddenly worked again. I don't know what must have changed to get it to work, but I suppose it's fixed now!

**Comment by xldenis** [comment] 2021-03-05 08:50
What OS are you on?

**Comment by ch869** [comment] 2021-03-05 12:00
I'm on Windows 10 Home.

**Comment by xldenis** [comment] 2021-03-06 19:58
Hmm, I have no idea what could be the cause, if this reoccurs please let me know, in the mean time I think i'll close this issue, is that alright with you?

**Closed by xldenis** 2021-03-06 19:58 UTC
